### ISSUE TITLE
Improve VerseRef.TrySetVerseUnicode by handling non-decimal numerals and surrogate pair numerals.

### ISSUE THREAD

**Issue by SamDelaney** [sillsdev/libpalaso#1000]
This change would allow applications to more easily and broadly use vernacular versification.

The methods char.IsDigit and char.GetNumericValue (used in VerseRef.TryGetVerseNum) only handle base-10, non-surrogate numerals (Complete list [here](https://www.fileformat.info/info/unicode/category/Nd/list.htm)). A broader alternative to these methods would have to be found or made.

The value calculation in TrySetVerseUnicode also currently assumes a decimal base:
`vNum = (short)(vNum * 10 + (romanOnly ? ch - '0' : char.GetNumericValue(ch)));`
This would have to be changed.

See discussion on #999 for additional context and (ignored) test cases.

**Comment by ermshiperete** [comment]
.NET 5 (and .NET Core 3+) has `Rune.IsDigit` and `Rune.GetNumericValue` methods that can deal with surrogate pairs.

Alternatively this could be implemented with `Char.IsDigit`/`Char.IsNumber` and `Char.IsSurrogate` to identify the first part of the string that represents the number and `Int32.TryParse` to convert the first part of the string to a number.
