### ISSUE TITLE
Chorus: Verify that using the designer for winforms projects is still possible on Windows

### ISSUE THREAD

**Issue by ermshiperete** [sillsdev/libpalaso#1002]
- [x] test using the designer with VS 2019 16.8 in the projects
- [x] remove separate Designer projects that were added as a hack
- [x] test building on Linux

**Comment by ermshiperete** [comment]
sillsdev/chorus#224 currently fails on AppVeyor, maybe because it doesn't yet have the current VS version available

**Comment by RaymondLuong3** [comment]
Observations:
1. The designer works on master branch, but when I switch feature/nuget, opening the designer gives a "The extender provider could not provide the extender."
2. No progress removing the separate designer projects.
3. Building on Linux succeeded, but both on master and feature/nuget branch there are roughly 200  test errors with (System.IO Exception: Too many open files)

Notes on building chorus: Using Wasta 18.04 and mono 6.

**Comment by RaymondLuong3** [comment]
![Chorus_Tests](https://user-images.githubusercontent.com/17931130/101674972-6568f180-3a16-11eb-96ae-ec46a28fbe86.PNG)

**Comment by ermshiperete** [comment]
>     3\. Building on Linux succeeded, but both on master and feature/nuget branch there are roughly 200  test errors with (System.IO Exception: Too many open files)

You'll have to increase the file limit in your system. See e.g. https://askubuntu.com/questions/1049058/how-to-increase-max-open-files-limit-on-ubuntu-18-04.

I have the following two lines in my `/etc/security/limits.conf` file:

```
eberhard        soft    nofile          65536
eberhard        hard    nofile          65536
```
