### ISSUE TITLE
FlexBridge: Verify that using the designer for winforms projects is still possible on Windows

### ISSUE THREAD

**Issue by ermshiperete** [sillsdev/libpalaso#1003]
- [x] test using the designer with VS 2019 16.8 in the projects
- [ ] remove separate Designer projects that were added as a hack
- [x] test building on Linux

**Comment by papeh** [comment]
I see nothing that looks like a hacked Designer project. All designer forms worked without modification in VS 2019 16.8.2, so I assume Linux builds will continue to succeed.

**Comment by papeh** [comment]
Builds and all tests pass on my fwdev-w1804 Vagrant and the xenial64 build agent.
