### ISSUE TITLE
liblcm: Verify that using the designer for winforms projects is still possible on Windows

### ISSUE THREAD

**Issue by ermshiperete** [sillsdev/libpalaso#1004]
- [x] [test designer](1027)
- [x] remove separate Designer projects that were added as a hack - does not apply
- [x] test building on Linux - waiting on https://github.com/sillsdev/liblcm/pull/164

**Comment by tombogle** [comment]
@ermshiperete The only Designer files I see in this solution are for resx files containing string resources. They do open just fine in VS. I don't see any separate Designer projects that were added. I looked in both the master and nuget branches. Either I'm missing something, or this doesn't actually apply to liblcm.

**Comment by ermshiperete** [comment]
@tombogle Looks this doesn't apply to liblcm. When I originally created the task I checked for references to `System.Windows.Forms.dll` but didn't check if there are actually dialogs in the project, nor if there is a *Designer.csproj file.
