### ISSUE TITLE
document developing/debugging a project with dependencies that are now nuget packages

### ISSUE THREAD

**Issue by ermshiperete** [sillsdev/libpalaso#1009]

**Comment by ermshiperete** [comment]
I started a wiki page: https://github.com/sillsdev/libpalaso/wiki/Developing-with-nuget-packages. This probably needs to be a little extended.

**Comment by marksvc** [comment]
I added a couple examples for using locally-modified assemblies when working with msbuild and mono 6. But IIRC, dotnet overwrites attempts to use locally-modified assemblies, so a dotnet examples would be good to add as well.

**Comment by papeh** [comment]
Running `msbuild /t:pack` on a machine with `LOCAL_NUGET_REPO` set will publish local packages for Palaso, Chorus, and LCM. L10nSharp doesn't have the `pack` target readily available when using my VS2019 custom tool (described in Eberhard's wiki), so I've not added the publish locally target to L10nSharp.
