### ISSUE TITLE
LfMerge: make the feature/nuget branch the main development branch

### ISSUE THREAD

**Issue by ermshiperete** [sillsdev/libpalaso#1015]
- [x] merge `master` into `feature/nuget` again
- [x] announce that the merge of the `feature/nuget` branch will be made the main development branch
- [x] merge `feature/nuget` into `master`. Doing this requires adjusting the path to the `CHANGELOG.md` file in the .csproj as well as adjusting `GitVersion.yml` (removing settings for `feature/nuget` branch).

**Comment by rmunn** [comment]
LfMerge `master` is already merged into `feature/nuget`: merging the other direction (`feature/nuget` into `master`) is a simple fast-forward merge. So I've checked off the first task item.
