### ISSUE TITLE
Create release nuget packages of dependent projects

### ISSUE THREAD

**Issue by ermshiperete** [sillsdev/libpalaso#1018]
- [x] Identify the projects we depend on that we control and that still have pre-release version numbers, e.g. L10NSharp
- [x] Create a release for those

**Comment by sujeffreyl** [comment]
I went through all the projects in LibPalaso, looked up their Nuget package page, checked dependencies, and looked for dependencies that we control that are in prerelease that are not in LibPalaso itself.

The only one matching those conditions is L10NSharp.
