### ISSUE TITLE
NuGet Sprint: Fix the NUnitReport project to work with the new output locations

### ISSUE THREAD

**Issue by jasonleenaylor** [sillsdev/libpalaso#1038]
Running NUnitReport with the current SDK project files and their outputs fails finding no tests.

Adjust NUnitReport to look in the new output folder or evaluate if NUnitReport is still useful given the way tests are run now.

**Comment by ermshiperete** [comment]
https://gerrit.lsdev.sil.org/c/FieldWorks/+/7947
