### ISSUE TITLE
Update SIL logo

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/libpalaso#1328]
We're using the square logo here https://github.com/sillsdev/libpalaso/blob/e5745ec04c507a18bfe6b67c29c177713ec1a15d/SIL.Windows.Forms/Resources/SILLogoBlue101x113.png and we should use the proper rectangular logo

**Comment by tombogle** [comment]
Since I raised this issue, I've assigned it to myself, but if someone else wants to work on it before I get around to it, let me know, and I will happily relinquish my rights.
