### ISSUE TITLE
LanguageChooser should not show all the country variants of multiple languages

### ISSUE THREAD

**Issue by hatton** [sillsdev/libpalaso#315]
For the applications that use this dialog (WeSay, Bloom) people should always be choosing just "en", "fr", etc. The on exception to this is  Chinese Mandarin which ends up being zh-CN.

![image](https://cloud.githubusercontent.com/assets/8448/11009536/f401eff6-8494-11e5-8bb5-d7e5a6920d8e.png)

**Comment by cambell-prince** [comment]
Maybe we should make this settable by the client, with default being to show the minimum.  @hatton There's been some discussion about FLEx users wanting to compare dialects or regional language variation in which case these may be helpful.

**Comment by hatton** [comment]
A setting would be fine. However don't know who would ever use those other
settings. FLEx & WeSay let the users add location and script and other
variation information on their own, through more detailed dialogs, and I
think any future linguistic apps would do the same. The approach of just
listing all possible variations (country, script, dialect) is...
inappropriate, ux-wise.

On Fri, Nov 6, 2015 at 8:02 PM, Cambell <notifications@github.com> wrote:

> Maybe we should make this settable by the client, with default being to
> show the minimum. @hatton <https://github.com/hatton> There's been some
> discussion about FLEx users wanting to compare dialects or regional
> language variation in which case these may be helpful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sillsdev/libpalaso/issues/315#issuecomment-154607786>.
>



-- 

John Hatton

Senior Software Engineer/Program Manager
Language Software Development
SIL International

**Comment by ddaspit** [comment]
If you manually change the script and region after the fact, then you won't download the correct LDML file from the SLDR. Each of these entries corresponds to a different LDML file in the SLDR/CLDR. They are listed here, so the application knows which LDML file to download from the SLDR. If the user selected "English" and then changed the region to "US" manually, the generic "en" LDML would be downloaded with none of the specific settings for the "en-US" dialect. I would suggest adding an option to the dialog that allows the user to show all dialects, i.e. a checkbox with the label, "Show all dialects", that is unchecked by default.
