### ISSUE TITLE
Structure of alltags.txt ?

### ISSUE THREAD

**Issue by matsbla** [sillsdev/libpalaso#533]
I checked this file;
https://github.com/sillsdev/libpalaso/blob/master/SIL.WritingSystems/Resources/alltags.txt
Why does some of the tags have a star in front of them and others have not?
Is there a documentation somewhere on how this file is structured?

**Comment by ermshiperete** [comment]
`alltags.txt` comes from the SLDR. The documentation of the file format is on the [SLDR wiki](https://github.com/silnrsi/sldr/blob/master/doc/alltags.md).

(You probably saw the [SIL.WritingSystems](https://github.com/sillsdev/libpalaso/wiki/SIL.WritingSystems) wiki page, but that didn't link to the SLDR wiki until now :smile: )

**Comment by matsbla** [comment]
Aha, I see! Now it is clear, thanks for the feedback =)
