### ISSUE TITLE
Test output on stderr is treated as an error iff Verbose flag is on

### ISSUE THREAD

**Issue by rmunn** [sillsdev/libpalaso#635]
In [this section of TestTask.cs](https://github.com/sillsdev/libpalaso/blob/8badb161e60d0732ff12b4ef768b4d9707b33a3c/SIL.BuildTasks/UnitTestTasks/TestTask.cs#L293), the Verbose flag causes anything on stderr to be logged as an error. This is causing build failures like [this one](https://build.palaso.org/viewLog.html?tab=buildLog&buildTypeId=WeSay15_Wesay16xenial64continuous&buildId=111062&_focus=6095) where GDK *warnings* that were logged to stderr are being treated (incorrectly) as errors and causing a build failure when there's no actual problem with the build.

A lot of Linux software treats stderr not as a place to print error messages, but as a place to print *any* notification that is meant for the user to see even though he might be redirecting stdout. E.g., progress messages, and so on. We should change the logic in TestTask.cs to not consider stderr output as an error.

Also, the Verbose flag is [documented](https://github.com/sillsdev/libpalaso/blob/8badb161e60d0732ff12b4ef768b4d9707b33a3c/SIL.BuildTasks/UnitTestTasks/TestTask.cs#L51) as "If `true` print the output of NUnit immediately, otherwise print it ater [sic] NUnit finished". Yet it's the Verbose flag that's being used to treat stderr output as an error, which means it changes the semantics of how stderr is treated. This made it rather hard to track down this issue, as it's not at all obvious from that documentation that Verbose is going to change the behavior of the TestTask class.

**Comment by megahirt** [comment]
I suggest either Log.LogError() to Log.LogMessage() in accordance with what Robin is saying that the intention of stderr message does not equate to a program failure, but rather messages intended for the user to see.  Another option is to add an additional parameter/flag FailOnStderr that will cause the build to fail on stderr.  It seems like this is unlikely to ever be a desired option, so coding this functionality is probably not worth it.

**Comment by ermshiperete** [comment]
> A lot of Linux software treats stderr not as a place to print error messages, but as a place to print any notification that is meant for the user to see even though he might be redirecting stdout. E.g., progress messages, and so on. We should change the logic in TestTask.cs to not consider stderr output as an error.

The question then is how do you distinguish between an error (that should fail the build) and other informational messages. E.g. when NUnit crashes we want to fail the build otherwise the tests would look like they all passed.

**Comment by ermshiperete** [comment]
NUnit does return a non-zero error code when it crashes. But it also returns a non-zero error code if some tests fail. So by looking at the error code we don't know whether it's a test failure or a crash. But it looks like @glasseyes found a solution in #636, and #637 adds additional tests, so I'm happy now.

**Comment by glasseyes** [comment]
[#636](https://github.com/sillsdev/libpalaso/pull/636) is now merged,
