### ISSUE TITLE
SelectProjectDlgBase should not access abstract properties in the constructor.

### ISSUE THREAD

**Issue by tombogle** [sillsdev/libpalaso#797]
There's no actual need to initialize m_fileDialog (etc.) until we actually get ready to show the dialog for the first time. By accessing abstract properties in the constructor, it prevents Subclasses from having arguments passed in to their constructors that might be needed to implement the abstract members. In this case, there are times when subclasses might need to have a more meaningful Title based on something that is not static.

**Comment by ermshiperete** [comment]
Suggestion: new method `protected virtual OpenFileDialog CreateFileDialog()` that gets called at the beginning of `ShowDialog`.
