### ISSUE TITLE
[WritingSystems] alltags renamed to langtags

### ISSUE THREAD

**Issue by glasseyes** [sillsdev/libpalaso#810]
The alltags.json file is now langtags.json in the upstream WS Tech sldr repo
The update url for alltags.json 

The cached file in SIL.WritingSystems/Resources needs to be changed and in LanguageRegistryResources
The code in SIL.WritingSystems/Sldr.cs needs to be updated to update the new file
plus any comments that refer to alltags

**Comment by jasonleenaylor** [comment]
This work has now been completed
