### ISSUE TITLE
SIL.Windows.Forms.Keyboarding is missing Keyman10Interop dll

### ISSUE THREAD

**Issue by ermshiperete** [sillsdev/libpalaso#865]
This leads to a crash:

```
Msg: Could not load file or assembly 'Keyman10Interop, Version=10.0.0.0, Culture=neutral, PublicKeyToken=e33b67d3bb5581e4' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Class: System.IO.FileLoadException
Source: SIL.Windows.Forms.Keyboarding
Assembly: SIL.Windows.Forms.Keyboarding, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cab3c8c5232dfcf2
Stack:    at SIL.Windows.Forms.Keyboarding.Windows.KeymanKeyboardAdaptor.GetInstalledKeymanVersion()
  at SIL.Windows.Forms.Keyboarding.KeyboardController.SetDefaultKeyboardAdaptors()
  at SIL.Windows.Forms.Keyboarding.KeyboardController.Initialize(IKeyboardRetrievingAdaptor[] adaptors)
  at SIL.Transcelerator.TxlPlugin.<>c__DisplayClass9_0.<Run>b__0() in C:\Projects\Transcelerator\Transcelerator\TxlPlugin.cs:line 151
  at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
  at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
  at System.Threading.ThreadHelper.ThreadStart()
Thread: Transcelerator
Thread UI culture: en-US
Exception: System.IO.FileLoadException
--Error Reporting Properties--
Version: 1.3.0.0 (apparent build date: 9/25/2019)
CommandLine: "C:\Windows\Microsoft.NET\Framework\v4.0.30319\AddInProcess32.exe" /guid:9733f9a6-c557-4203-b92b-d21dcaec29b6 /pid:21204
CurrentDirectory: C:\Program Files (x86)\Paratext 9
MachineName: SWD-BOGLE-LT
OSVersion: Windows 10
DotNetVersion: 4.0.30319.42000
WorkingSet: 23691264
UserDomainName: WAXHAW
UserName: Bogle
Culture: en-US
Plugin Name: Transcelerator
Host Application: Paratext 9.0.63.5
```

**Comment by ermshiperete** [comment]
This is probably caused by the fact that we don't ship the Interop dll. What's worse is that we create a strong-named version of the Interop dll. Usually it's not strong-named, so even if the client adds the Interop it doesn't work.

It might be best to define the interfaces we use from Keyman in our code instead of referencing the Interop dll.

We should also check the other projects for additional Interop dlls, and check any non-strong-named assembly that we depend on (and that we strong-name with the help of StrongNamer).

Another option is to simply ship the strong-named version of the Interop dll, but this could cause conflicts if another assembly comes with a different version of the Interop dll.

A third option is to use `ilmerge` to embed the Interop dll inside of our assembly. This should work well if we don't expose anything from the Interop in our API. We might want to use this option for other dependencies where we can't simply redefine the interop interface.

**Comment by tombogle** [comment]
Please also check KeymanLink.dll and Keyman7Interop.dll. I currently download them from the TC build. So far it only complains about Keyman10Interop, but it may be that that's the first one it attempts to load.

**Comment by jwickberg** [comment]
Just found this issue - I'm now having the same problem in Paratext. We have updated Paratext to use the new nuget packages in work that is being done for Paratext 9.1, but we can't run Paratext because of this error.

Any conclusion on what should be done?

**Comment by ermshiperete** [comment]
A similar issue exists with ibusdotnet - I guess it only affects Linux. The solution for that is to create a nuget package with a signed version of `ibusdotnet.dll`.

**Comment by ermshiperete** [comment]
Fixed.
